# Generated by Django 4.2 on 2025-08-05 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_words', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('root_cause', models.TextField(blank=True)),
                ('root_cause_file', models.FileField(blank=True, null=True, upload_to='root_cause/')),
                ('solutions', models.TextField(blank=True)),
                ('solutions_file', models.FileField(blank=True, null=True, upload_to='solutions/')),
                ('others', models.TextField(blank=True)),
                ('others_file', models.FileField(blank=True, null=True, upload_to='others/')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
    ]
